# Generated by Django 5.2.12 on 2026-03-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matric_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
