# Generated by Django 5.2.12 on 2026-03-28 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_verification_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
