# Generated by Django 5.2.12 on 2026-03-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_verification_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='programme_duration',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
